<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="UnDosTres" duration-ms="195376" started-at="2020-10-06T13:38:38 IST" finished-at="2020-10-06T13:41:53 IST">
    <groups>
    </groups>
    <test name="UnDosTres HomePage" duration-ms="195376" started-at="2020-10-06T13:38:38 IST" finished-at="2020-10-06T13:41:53 IST">
      <class name="org.UnDosTres.test.PaymentDetailPageTest">
        <test-method status="PASS" signature="beforeStartOfClass()[pri:0, instance:org.UnDosTres.test.PaymentDetailPageTest@55322aab]" name="beforeStartOfClass" is-config="true" duration-ms="10" started-at="2020-10-06T13:38:38 IST" finished-at="2020-10-06T13:38:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeStartOfClass -->
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:org.UnDosTres.test.PaymentDetailPageTest@55322aab]" name="setUp" is-config="true" duration-ms="56277" started-at="2020-10-06T13:38:38 IST" finished-at="2020-10-06T13:39:34 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@36f6d25c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validatePaymentHasBeenCompletedThroughCard()[pri:3, instance:org.UnDosTres.test.PaymentDetailPageTest@49cb9cb5, instance params:[Chrome, Telcel, 5523261151, Recarga Saldo, 10, Test, 4111111111111111, 11, 2025, 111, test@test.com, automationexcersise@test.com, 123456, yes]]" name="validatePaymentHasBeenCompletedThroughCard" duration-ms="23878" started-at="2020-10-06T13:39:34 IST" finished-at="2020-10-06T13:39:58 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to submit recharge as Pop Up Is not getting disappear expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to submit recharge as Pop Up Is not getting disappear expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.UnDosTres.test.PaymentDetailPageTest.validatePaymentHasBeenCompletedThroughCard(PaymentDetailPageTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePaymentHasBeenCompletedThroughCard -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.UnDosTres.test.PaymentDetailPageTest@55322aab]" name="tearDown" is-config="true" duration-ms="718" started-at="2020-10-06T13:39:59 IST" finished-at="2020-10-06T13:39:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:org.UnDosTres.test.PaymentDetailPageTest@55322aab]" name="setUp" is-config="true" duration-ms="36601" started-at="2020-10-06T13:39:59 IST" finished-at="2020-10-06T13:40:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@36f6d25c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validatePaymentHasBeenCompletedThroughCard()[pri:3, instance:org.UnDosTres.test.PaymentDetailPageTest@4ff4357f, instance params:[FireFox, Telcel, 5523261151, Recarga Saldo, 10, Test, 4111111111111111, 11, 2025, 111, test@test.com, automationexcersise@test.com, 123456, yes]]" name="validatePaymentHasBeenCompletedThroughCard" duration-ms="11539" started-at="2020-10-06T13:40:36 IST" finished-at="2020-10-06T13:40:47 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to submit recharge as Pop Up Is not getting disappear expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to submit recharge as Pop Up Is not getting disappear expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.UnDosTres.test.PaymentDetailPageTest.validatePaymentHasBeenCompletedThroughCard(PaymentDetailPageTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePaymentHasBeenCompletedThroughCard -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.UnDosTres.test.PaymentDetailPageTest@55322aab]" name="tearDown" is-config="true" duration-ms="1284" started-at="2020-10-06T13:40:48 IST" finished-at="2020-10-06T13:40:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:org.UnDosTres.test.PaymentDetailPageTest@55322aab]" name="setUp" is-config="true" duration-ms="38128" started-at="2020-10-06T13:40:49 IST" finished-at="2020-10-06T13:41:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@36f6d25c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validatePaymentHasBeenCompletedThroughCard()[pri:3, instance:org.UnDosTres.test.PaymentDetailPageTest@55322aab, instance params:[Edge, Telcel, 5523261151, Recarga Saldo, 10, Test, 4111111111111111, 11, 2025, 111, test@test.com, automationexcersise@test.com, 123456, yes]]" name="validatePaymentHasBeenCompletedThroughCard" duration-ms="24426" started-at="2020-10-06T13:41:27 IST" finished-at="2020-10-06T13:41:52 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to submit recharge as Pop Up Is not getting disappear expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to submit recharge as Pop Up Is not getting disappear expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.UnDosTres.test.PaymentDetailPageTest.validatePaymentHasBeenCompletedThroughCard(PaymentDetailPageTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePaymentHasBeenCompletedThroughCard -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.UnDosTres.test.PaymentDetailPageTest@55322aab]" name="tearDown" is-config="true" duration-ms="1203" started-at="2020-10-06T13:41:52 IST" finished-at="2020-10-06T13:41:53 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.UnDosTres.test.PaymentDetailPageTest -->
    </test> <!-- UnDosTres HomePage -->
  </suite> <!-- UnDosTres -->
</testng-results>
